name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.3.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build and test
        run: mvn --batch-mode --update-snapshots verify
      - name: Test Reporter
        uses: dorny/test-reporter@v1.7.0
        if: always()
        with:
          name: Test results
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: 'java-junit'
